package ru.snt.portal.ui.theme

import androidx.compose.ui.graphics.Color

val mdThemeLightPrimary = Color(0xFF6750A4)
val mdThemeLightOnPrimary = Color(0xFFFFFFFF)
val mdThemeLightSecondary = Color(0xFF625B71)
val mdThemeLightOnSecondary = Color(0xFFFFFFFF)
val mdThemeLightTertiary = Color(0xFF7D5260)
val mdThemeLightOnTertiary = Color(0xFFFFFFFF)
val mdThemeLightError = Color(0xFFB3261E)
val mdThemeLightOnError = Color(0xFFFFFFFF)
val mdThemeLightBackground = Color(0xFFFFFBFE)
val mdThemeLightOnBackground = Color(0xFF1C1B1F)
val mdThemeLightSurface = Color(0xFFFFFBFE)
val mdThemeLightOnSurface = Color(0xFF1C1B1F)
val mdThemeLightSurfaceVariant = Color(0xFFE7E0EC)
val mdThemeLightOnSurfaceVariant = Color(0xFF49454F)

val mdThemeDarkPrimary = Color(0xFFD0BCFF)
val mdThemeDarkOnPrimary = Color(0xFF381E72)
val mdThemeDarkSecondary = Color(0xFFCCC2DC)
val mdThemeDarkOnSecondary = Color(0xFF332D41)
val mdThemeDarkTertiary = Color(0xFFEFB8C8)
val mdThemeDarkOnTertiary = Color(0xFF492532)
val mdThemeDarkError = Color(0xFFF2B8B5)
val mdThemeDarkOnError = Color(0xFF601410)
val mdThemeDarkBackground = Color(0xFF10131A)
val mdThemeDarkOnBackground = Color(0xFFE5E1E8)
val mdThemeDarkSurface = Color(0xFF10131A)
val mdThemeDarkOnSurface = Color(0xFFE5E1E8)
val mdThemeDarkSurfaceVariant = Color(0xFF49454F)
val mdThemeDarkOnSurfaceVariant = Color(0xFFCAC4D0)
